### ISSUE TITLE
#1 Toolbar and Tab Layout are not properly constrained 

### ISSUE THREAD

**Issue by MasterBlaster99** [DeepaliVerma011/GEET#1]
![WhatsApp Image 2021-03-28 at 12 18 19 AM](https://user-images.githubusercontent.com/71667923/112731083-3e014a80-8f5b-11eb-92be-a02f6c802574.jpeg)

**Comment by DeepaliVerma011** [comment]
okay @MasterBlaster99 you willing to solve this issue?

**Comment by MasterBlaster99** [comment]
> okay @MasterBlaster99 you willing to solve this issue?

@DeepaliVerma011 i have solved , check pull request.

**Comment by MasterBlaster99** [comment]
@DeepaliVerma011  please close this issue as it is solved
