### ISSUE TITLE
#2 Heading looks like Buttons

### ISSUE THREAD

**Issue by MasterBlaster99** [DeepaliVerma011/GEET#3]
In About and Privacy Policy activities the Headings look like Buttons. Instead of using such headings i will just add  a ActionBars respectively.

![WhatsApp Image 2021-03-28 at 1 33 31 AM (1)](https://user-images.githubusercontent.com/71667923/112733798-1b296300-8f68-11eb-8c1c-5745c45d9a3b.jpeg)
![WhatsApp Image 2021-03-28 at 1 33 31 AM](https://user-images.githubusercontent.com/71667923/112733805-1ebcea00-8f68-11eb-8da1-2a05c91dd2fd.jpeg)

**Comment by DeepaliVerma011** [comment]
you solved this issue?

**Comment by MasterBlaster99** [comment]
> you solved this issue?

@DeepaliVerma011  Not yet but i am working on it

**Comment by DeepaliVerma011** [comment]
okay sure. Thanks for contributing..

**Comment by MasterBlaster99** [comment]
> okay sure. Thanks for contributing..

My Pleasure
